name: Daily Dingtalk Push

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        playwright install chromium  # ✅ 安装浏览器驱动

    - name: Run script
      run: python dingtalk_push.py
